- MAINTAINERS.md
- README.md
- community-members.md
community membership document that explains the process of becoming member, approver or maintainer will be published next Monday. This is initial document that show how we can structure the initial list. Let's fill it up thru PRs. Going forward specific repositories approvers and maintainers will be listed in the corresponding repositories.
> This is an initial list of maintainers to bootstrap it

- community-members.md
> approver for C#

- community-members.md
@pjanotti nominating you as maintainer for agent/collector. Let me know if there are problems with this.
> Nominations for agent and collector

- community-members.md
@mayurkale22 nominating based on Open Census work. 
> nominating for node.js

- community-members.md
@rghetia nominating based on Open Census. 
> nominate for golang

- community-members.md
Nominate Steven for Approver on agent/collector and GoLang
> Nominate Steven

- community-members.md
Nominating Justin based on OpenCensus work.
@justindsmith please confirm you are up for being a maintainer.
(see #34)
> Nominating Justin

- community-members.md
Nomination, not a full list. 
@mtwo @flands please confirm you are up for this.
> Nomination for docs and website

- README.md
Let's see if we can do 9 AM Tuesdays. We have couple people from MS joining as well
CC: @gregkalapos @austinlparker
> Dotnet sig sync up proposal.

- community-members.md
Nominating thru OpenCensus involvement. @flands please indicate your readiness for this
> Nominate Steve for service

- community-members.md
@songy23 please approve or like this PR.
> Add Yang as an approver for Java

- CONTRIBUTING.md
- community-membership.md
Updating CONTRIBUTING with a small change so "Contributing" becomes a subheader.
Updating community-membership to link to CONTRIBUTING.md when mentioning the "Have read the..."
> Documentation updates

- community-members.md
> Nominate Francis Bogsanyi as Ruby maintainer

- README.md
Hopefully this is uncontroversial... I've been getting folks asking me "how they can help" via email, and I'd like it to be easier for them to answer that question themselves. :)
> Add link to new-contributor form

- community-members.md
@bai, what's your company affiliation?
> Added bai as approver for Ruby

- governance-charter.md
Authored and reviewed by @bhs @bogdandrutu @SarahNovotny @SergeyKanzhelev @yurishkuro
> governance charter document

- README.md
@open-telemetry/technical-committee
@open-telemetry/specs-approvers 
@danielkhan 
@pavolloffay 
What time will work the best? We probably want to do it early morning pacific time. As we don't have Asia yet. 
I was thinking Thursday or Tuesday 8 AM pacific? Please list your preference
> specifications SIG

- community-members.md
> Nominating Reiley as an additional specs approver

- initial-milestones.md
Replaces #50 
@tedsuo I didn't have permissions to update your PR so submitting a separate one
> Initial Milestones

- README.md
As was asked in https://github.com/open-telemetry/opentelemetry-node/issues/33
> Add license information

- community-members.md
as per @fbogsany request based on Ruby SIG meeting discussion
> Nominating @luvtechno as Ruby approver

- README.md
> Removed SIG form

- community-members.md
> Nominating Josh as Go approver

- community-members.md
- PRs reviewed: Almost all the PRs so far (https://github.com/open-telemetry/opentelemetry-js/pulls), more than 25.
- Issues responded to: Almost all the issues so far (https://github.com/open-telemetry/opentelemetry-js/issues), more than 30. 
- Involved in SIG meetings.
> Nominating @rochdev as Node.js approver

- README.md
- community-members.md
see https://github.com/open-telemetry/opentelemetry-js/issues/20 for motivation
> Rename references nodejs to javascript

- community-members.md
Fixes https://github.com/open-telemetry/community/issues/144.
> Nominating @songy23 as Service approver

- README.md
Same as https://github.com/open-telemetry/community/pull/147
> Link to shared calendar for js SIG

- community-members.md
- PRs reviewed: More than 25.
1. https://github.com/open-telemetry/opentelemetry-js/pull/154#pullrequestreview-270219345
1. https://github.com/open-telemetry/opentelemetry-js/pull/88#discussion_r301793721
1. https://github.com/open-telemetry/opentelemetry-js/pull/73#discussion_r299705760
1. https://github.com/open-telemetry/opentelemetry-js/pull/45#discussion_r296923761
1. https://github.com/open-telemetry/opentelemetry-js/pull/57#discussion_r297382177
1. https://github.com/open-telemetry/opentelemetry-js/pull/102#pullrequestreview-261986501
- List of PRs: https://github.com/open-telemetry/opentelemetry-js/pulls?q=is%3Apr+author%3Abg451+is%3Aclosed
- Involved in SIG meetings.
- Nominated by a maintainer - **YES**
> Nominating @bg451 as JavaScript approver

- community-members.md
- PRs reviewed: More than 15+.
1. https://github.com/open-telemetry/opentelemetry-js/pull/232#issuecomment-526712078
1. https://github.com/open-telemetry/opentelemetry-js/pull/231#discussion_r319463567
1. https://github.com/open-telemetry/opentelemetry-js/pull/128#issuecomment-514726545
1. https://github.com/open-telemetry/opentelemetry-js/pull/213
1. https://github.com/open-telemetry/opentelemetry-js/pull/126#pullrequestreview-266352334
1. https://github.com/open-telemetry/opentelemetry-js/pull/215#pullrequestreview-278717686
1. https://github.com/open-telemetry/opentelemetry-js/pull/205#pullrequestreview-278143409
1. https://github.com/open-telemetry/opentelemetry-js/pull/223
1. https://github.com/open-telemetry/opentelemetry-js/pull/217
1. …
> Nominating @OlivierAlbertini as JavaScript approver

- README.md
Thanks @tsloughter for leading this group
> Add Erlang SIG group

- docs/how-to-configure-new-repository.md
> Addresses #41

- community-membership.md
> We decided to not introduce the triager role. Just combine it with approver

- 2019-governance-committee-election.md
This is the election process and a schedule document for the 2019 governance committee election.
CC: @bhs, @bogdandrutu, @sarahnovotny, @yurishkuro
> Voting process and schedule for the 2019 governance committee election

- README.md
We aren't using MS Teams anymore.
> Update Link & Phone numbers for Spec SIG

- README.md
Meet weekly from next week through Kubecon
> Added website SIG

- community-members.md
Do not merge this until @spirosx approves it.
> Rename Omnition with Splunk

- 2019-governance-committee-candidates.md
We will add bios + (optional) photos after ratification.
> Publish the list of OpenTelemetry Governance Committee candidates

- community-members.md
> Decentralizing the .NET members

- community-members.md
Related to: #233 and https://github.com/open-telemetry/community/pull/234#issuecomment-546555533
> Decentralizing the JavaScript members

- community-members.md
> Update mwear affiliation

- community-members.md
I am not capable of reviewing any important PR in that repo, and cannot follow everything that happens there.
> Remove myself from golang approver list.

- community-members.md
> Decentralizing the Python members 

- README.md
Now that we are getting going and have more to discuss.
> Update Java Auto-Instrumentation meeting to weekly

- community-members.md
https://github.com/open-telemetry/opentelemetry-java/pull/759
> Move approvers/maintainers for Java in the java repo

- community-members.md
https://github.com/open-telemetry/opentelemetry-collector/pull/503
> Move approver/maintainer list for the collector

- README.md
> Add metrics SIG info

- README.md
> fix java calendar link

- community-membership.md
> Update membership to clarify who can merge approved PRs.

- community-membership.md
#308 updated only half of the date :-)
> Fix date in community-membership.md

- assets.md
> Add npm to assets file

- CONTRIBUTING.md
- docs/how-to-configure-new-repository.md
> switch to easybridge cla

- ADOPTERS.md
Coincides with https://github.com/open-telemetry/opentelemetry-collector/pull/1141
> Move Collector adopters to project-wide file

- ADOPTERS.md
> Add Jaeger to Adopters

- community-members.md
This is a followup from https://github.com/open-telemetry/opentelemetry-specification/pull/661
PS: Don't blame on me that I did not fork the repo, I do very few changes in community so I was lazy :)
> Update Specs and Proto approvers/maintainers

- docs/how-to-configure-new-repository.md
> Require EasyCLA for all properly configured repos

- community-members.md
Add @kumoroku and @zenmoto as initial Log approvers.
Resolves: https://github.com/open-telemetry/community/issues/399
> Add log approvers

- maturity-matrix.yaml
I am not sure if the yaml structure we have here is formally defined here.
I invented an "otlp" section here assuming that the file has informal
structure. If this is not so please correct me.
This is dependent on https://github.com/open-telemetry/opentelemetry-proto/pull/185
> Add OTLP maturity levels

- ADOPTERS.md
I work at Lightstep and we've adopted OpenTelemetry 🔭
> added Lightstep to the list of adopters

- CONTRIBUTING.md
- README.md
> Added notice about the file headers

- README.md
This is to address #489.
Sergey had some inputs on that about adding a link to the video as well, I've added a comment to the issue about that.
> Added link to meeting notes for both GC and TC

- elections/2020/governance-committee-election.md
Per #488, just cleaning up slightly before the Gitter announcement this eve.
(cc @SergeyKanzhelev @alolita @kateetak)
> Improve TODO dest links before publicizing

- tools/OpenTelemetryYoutube/OpenTelemetryYoutube/Program.cs
- tools/OpenTelemetryYoutube/README.md
> Adding governance conditions

- community-members.md
For community owners, this decision was already discussed and approved in the TC meeting.
> Add @anuraaga as specs approver

- elections/2020/governance-committee-election.md
This is a proposal, and needs at least 1/2 GC (5) members to approve it.
> Increase the deadline for nomination

- elections/2020/governance-committee-candidates.md
Addresses issue flagged in #536
> resize lizf.jpg

- elections/2020/governance-committee-election.md
Like #549 but without EasyCLA issues :)
cc @irabinovitch
> Fill in pre-reg link

- README.md
> Add Information about related groups

- community-members.md
This reflects the recent results from the 2020 election (see #488).
cc @alolita @dyladan @lizthegrey @mtwo
> Update the Governance Committee

- assets.md
Also morgan's google corp e-mail is not actual any longer. @mtwo, pls request access any time if needed for other account
> Added Alolita as a channel manager

- community-members.md
This was discussed among the TC and with @iNikem. @iNikem thank you for all the work you are putting to move the traces specification forward!
> propose @iNikem as trace approver

- assets.md
> Added  Ted Young to Youtube managers list

- marketing-guidelines.md
Propose marketing guidelines for organizations contributing to OpenTelemetry. Ported from [this google doc](https://docs.google.com/document/d/1pnjUjV5AT0hG16TY7aUcGcPW_1NjfWWzbcf-yvGM6OA/edit#). See also [this other google doc](https://docs.google.com/document/d/1pwYh_jilvoidvZ8qhe1iA8hXcrbdRFF2IKbJjXd7u3s/edit#heading=h.38pmc4ohxh26) which was the primary inspiration.
Closes #564.
> Marketing guidelines for OTel-contributing orgs

- assets.md
.NET is using GitHub actions now
> Azure pipelines only needed for .NET Instrumentation

- docs/how-to-handle-public-calendar.md
Please review PR AND the document linked.
> zoom bombing document

- community-members.md
@open-telemetry/technical-committee please review
/cc @jsuereth
> Add jsuereth as spec approver

- README.md
> Add a link to the CNCF Slack

- ADOPTERS.md
Adding Care.com to the list of adopters.
> doc(adopters): add Care.com to ADOPTERS.md

- community-membership.md
Technical consensus is wonderful when we can get there... and when we can't, this process should help us "disagree and commit."
All comments welcome!
cc @open-telemetry/governance-committee @open-telemetry/technical-committee
> Add a process for SIGs to resolve tech conflicts

- README.md
According to @austinlparker (as shared out-of-band).
> Website meetings are every other week, and in the ET timezone

- CONTRIBUTING.md
> Update Gitter link to slack in contributing guideline

- .github/ISSUE_TEMPLATE/donation.md
- CONTRIBUTING.md
Also, fix a copy-pasta error of mine in the template itself:
> Link to the (new) "Donation" issue template

- CONTRIBUTING.md
TIL you can't wrap the `()` and `[]` on separate lines. Sorry for the noise, trying to do too many things at once. :-/
> Fix line wrap / link issue

- elections/2021/governance-committee-candidates.md
- elections/2021/governance-committee-election.md
edit: list of eligible voters moved from apendix to #852
> Add 2021 voting document

- areas-of-interest.md
> Add Daniel Dyla to areas of interest

- assets.md
- docs/how-meeting-recordings-upload-works.md
Fixed up assets page to make titles linke-able. Posted troubleshooting steps for video uploads missing
> how to troubleshoot missing recordings

- README.md
The meeting time has recently changed form 8:30am to 8:00am.
> Updated time of the Client Instrumentation SIG

- README.md
This addresses the request made in https://lists.cncf.io/g/cncf-opentelemetry-comms/message/307.
> Link community member list from README

- areas-of-interest.md
Reflect the fact that I recently joined the TC.
> Update Area of Interest for reyang

- community-membership.md
This is one of the primary distinctions of members from regular GitHub users.
> Emphasize that members can vote in GC elections

- elections/2022/governance-committee-election.md
> GC Elections - split nomination from ratification

- elections/2022/governance-committee-candidates.md
Fixed broken picture link for Alolita Sharma
> Fixed broken picture link in Alolita Sharma GC Nomination section

- elections/2022/governance-committee-candidates.md
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>
> Fix picture sizes for election 2022

- README.md
/cc @carlosalberto @codeboten 
~~I used the regular spec channel for the slack channel~~
Updated the channel to the one recommended by @codeboten
> Add configuration working group

- README.md
We don't really have good standards for where to put this, so I'm open to any "title" changes or location changes.
Tested links for accuracy.
> Added Semantic Conventions working group references

- README.md
Resolves #1031
cc @open-telemetry/rust-approvers
> Remove Rust SIG meeting time

- assets.md
to be more specific about what kind of token it is
> Update opentelemetrybot token secret name

- community-members.md
After much thinking I decided it's time to officially resign from TC.
I wasn't involved with the community to the level I wanted for some time now. I thought I will be able to come back to the project that I love. But the reality is that I cannot devote enough time and energy to it.
I have some plans and work in progress that touches OpenTelemetry, and hope to be connected to the project thru this work.
> SergeyKanzhelev leaving TC

- areas-of-interest.md
@SergeyKanzhelev has left the TC.
FYI @jack-berg in case you might want to add yourself in another PR.
> Update the TC Area of Interest by removing Sergey

- docs/how-to-configure-new-repository.md
Related to https://github.com/open-telemetry/community/issues/1533#issuecomment-1581292613
> Clarify dependabot and renovate branch protections

- .github/scripts/markdown-link-check-config.json
seems to be failing sporadically lately, better to just exclude it
https://github.com/open-telemetry/community/pull/1526#issuecomment-1581797215
https://github.com/open-telemetry/community/pull/1520#issuecomment-1584778573
> Fix link check failure

- README.md
This pull request documents the newly formed SIG Security.
> Add SIG Security

- .github/scripts/markdown-link-check-config.json
Related to #1608
I'm not opposed to removing the link altogether, but figured I'd send this in the meantime.
> Ignore link

- docs/using-github-extensions.md
To avoid back and forth like #1591, recommend a maintainer vote before installing 3rd party tools.
> Recommend maintainer vote before installing 3rd party tools

- docs/how-to-handle-public-calendar.md
I think this matches the wording to the intent (motivated by a small confusion in #1600).
> Clarify calendar permissions

- README.md
Updates FAAS meeting cadence to reflect SIG decision given attendance. 
@trask would you mind updating the calendar itself?
> update faas meeting cadence

- assets.md
> Add EasyCLA status page

- .github/ISSUE_TEMPLATE/repo-permissions.md
> Fix typo in issue template repo-permissions.md

- elections/2023/governance-committee-candidates.md
> Small word smithing on jpkroehling's nomination for 2023 elections

- README.md
> Add Event WG Project to readme

- README.md
We changed the meeting starting this week to happen on Thursdays instead of Wednesdays.
> Update system semconv meeting time

- docs/how-to-handle-public-calendar.md
> Update Zoom link setup

- community-members.md
> Update Alolita's affiliation

- .github/scripts/markdown-link-check-config.json
- assets.md
Wasn't sure where these new accounts fit so created a new category
> Update assets for new accounts

- CONTRIBUTING.md
- README.md
- areas-of-interest.md
- assets.md
- community-membership.md
- docs/how-meeting-recordings-upload-works.md
- docs/how-to-handle-public-calendar.md
- project-management.md
- projects/event-api.md
- working-groups/end-user/end-user-interviews/README.md
- working-groups/end-user/end-user-interviews/end-user-interview-outcomes/june-2022-techdevplatform.md
This PR fixes some typos across the community repository
> Fix some typos

- governance-charter.md
During this last election, we noticed a couple of places that could have better wording.
I believe this PR reflects what was discussed during the GC meeting that checked the eligibility of the candidates, and agreed to be made as suggestions only after the election has been completed.
> Tweaks to the election's eligibility criteria and company representation

- mission-vision-values.md
/cc @open-telemetry/docs-approvers @trask
> Fix headings and their anchors in mission-vision-values.md

- projects/config.md
- projects/event-api.md
Followup on #1884. Missed a few places. Sorry about that.
> Update @jack-berg status for projects

- .cspell.yaml
- projects/llm-semconv.md
This proposes a project and working group for establishing Semantic Conventions for LLM applications. 
This project aims to establish observability standards for Large Language Model (LLM) applications, focusing on API interactions and multi-step LLM frameworks.
> Propose project / working group for LLM Observability Semantic Conventions

- docs/how-to-handle-public-calendar.md
> Clarify google group

- .github/workflows/reusable-markdown-link-check.yml
A couple of issues in recent versions:
* https://github.com/tcort/markdown-link-check/issues/297
* https://github.com/tcort/markdown-link-check/issues/304
> Fix markdown-link-check

- projects/event-api.md
Just bringing the Event project file up to date with reality.
> Update Event project file

- assets.md
- docs/using-actuated.md
This adds a new documentation on using the actuated GitHub app.
> Add actuated doc

- .cspell.yaml
- projects/resources-and-entities.md
This proposes a new project and SIG to introduce the concept of Entities, extend the concept of Resources in order to solve a number of long-standing well-known problems with the Resource, described in the PR and linked documents.
Proposed on behalf of @tigrannajaryan and @jsuereth
> Project and SIG Proposal: Resources and Entities

- projects/llm-semconv.md
After project approval, we now have updated links for:
* Meeting Calendar
* Meeting Notes
* Project Board
* New PR with minimum attributes
These updates will help guide people landing at the project / wg charter page and looking for how to get involved.
@alolita @lmolkova @nirga
> Update project links for LLM Semantic Conventions

- community-members.md
I checked with @austinlparker after seeing his affiliation was inconsistent in this document, this PR fixes it to his current company.
> [chore] Fix community member affiliation

- project-template.md
Reword initial section of project template to request more information about the challenges that a proposed project aims to solve.
This prompts the author of a project proposal to consider the impact of delivering a project and the problems that it solves, without jumping straight into the solution. This helps in prioritising across multiple projects, but also helps users understand how the actions of a given project will benefit them.
> Include section for current challenges in project template

- areas-of-interest.md
Updating affiliation at the same time.
> update areas of interest for codeboten

- areas-of-interest.md
> Update areas of interest for jpkrohling

- .cspell.yaml
- projects/security.md
follow up on https://github.com/open-telemetry/community/pull/1838
> add new member to the security SIG

- projects/env-semconv.md
As per comment in original PR: https://github.com/open-telemetry/community/pull/2018#issuecomment-2096329384
Adding @greenhsu123 to Sustainability sig
> chore: add @greenhsu123 to the sustainability sig

- projects/sustainability-semconv.md
\+ renaming https://github.com/open-telemetry/community/blob/main/projects/env-semconv.md --> https://github.com/open-telemetry/community/blob/main/projects/sustainability-semconv.md
> Add missing title for sustainability semconv project

- projects/sustainability-semconv.md
Adds a project board for the Sustainability SemConv project
> Add Sustainability Semantic Conventions project board

- gc-check-ins.md
> Update gc-check-ins to add link to liaison

- projects/developer_experience.md
* Spell my name right
* Despite all appearances, I'm not actually on the TC
> Dev Experience typo

- projects/contributor-experience.md
fixes https://github.com/open-telemetry/community/pull/2162#discussion_r1668915297
> Add JamieDanielson to contributor-experience staff

- .cspell.yaml
- .github/scripts/markdown-link-check-with-retry.sh
- .github/workflows/reusable-markdown-link-check.yml
- Makefile
- areas-of-interest.md
- assets.md
- package-lock.json
- package.json
- Auto-generate table of content for markdown files
- Add makefile target for links check and use it from GH workflow
- Remove TOC markers from areas-of-interest.md because it does not work well with links check
> Add TOC generator

- projects/security-semconv.md
add the github project so everyone could check it out from SIG description
> add link to the github project

- docs/how-to-configure-new-repository.md
> Configure dependabot security alerts and updates on new repos

- .cspell.yaml
- projects/collector-v1.md
> Roadmap project: OpenTelemetry Collector v1

- guides/contributor/CLA.md
Extra spaces and capitalization
> Minor: Update CLA.md

- community-members.md
> Add missing emeritus entry in community-members.md

- areas-of-interest.md
Add area of interest for Marc Alff.
> Add area of interest (Marc Alff)

- .cspell.yaml
- projects/go-compile-instrumentation.md
(destination was removed in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6671)
> Fix broken link

- .github/ISSUE_TEMPLATE/gc_member_onboarding.md
Adds missing channel to GC onboarding template.
> [chore][.github] Add GC + End User SIG channel to onboarding template

- assets.md
(and re-organized the github action runners sections)
> Document new CNCF github action runners

- .cspell.yaml
- community-members.md
> [chore] Update jpkroehling's affiliation

- .cspell.yaml
- projects/otelarrow.md
See https://github.com/open-telemetry/otel-arrow/issues/294.
This includes content from https://github.com/open-telemetry/otel-arrow/blob/main/docs/project-phases.md.
> Add OTel-Arrow project definition

- projects/sampling.md
The Sampling SIG is ~4 years old, it's time for a project entry :-)
> Add Sampling project definition

- areas-of-interest.md
- community-members.md
> Update affiliation for Ted Young

- .lychee.toml
These links have been timing out a lot lately, proposing to just disable them
> Fix CI failures

- .github/workflows/build.yml
- .github/workflows/spell-check.yml
- .github/workflows/table-check.yml
- .github/workflows/toc-check.yml
This way we don't have to play the "update branch" game.
> Prepare for enabling merge queue

- docs/how-meeting-recordings-upload-works.md
Defines Zoom link spreadsheet archival process.
Follows #1431
Fixes #2646
> [docs] Add Zoom link spreadsheet archival policy

- Makefile
There have been breaking changes to `latest` recently.
> Pin lychee version

- areas-of-interest.md
- community-members.md
I’ve decided to step down from the TC, as my day job doesn’t align with TC responsibilities and my personal time goes to maintaining Jaeger.
> Yuri Shkuro stepping down from TC

- docs/how-to-configure-new-repository.md
Related to https://github.com/open-telemetry/community/issues/2860
> Add more secure workflow permissions to new repos going forward

- .github/ISSUE_TEMPLATE/sig-onboarding.yml
> Add SIG onoboarding issue template

- projects/gen-ai.md
Fixes link after content was moved
> Fix link to Arize Phoenix

- guides/contributor/membership.md
Fixes https://github.com/open-telemetry/community/issues/1842
> Clarify escalation paths for different concerns

- projects/mainframe.md
@gshriver replaced @youngaaronm as co-lead of the mainframe SIG.
> Update to project leads of Mainframe SIG

- areas-of-interest.md
- community-members.md
> Update jpkroehling's affiliation

- projects/new-getting-started-docs-and-reference-application.md
cc @svrnm in case you have preference for alternative
> Remove broken link

- README.md
- sigs.yml
adds the Romanian localization to the list
> Add `ro` localization team to sig list
