community-members.md

@bogdandrutu @carlosalberto @yurishkuro as discussed at morning meeting - I put our names as approvers on various languages to oversee APIs unification. Made myself maintainer for C# to not have a separate PR for this.

per language API oversee by TSC

---

community-members.md

@c24t, @reyang I'm nominating you as maintainers for OpenTelemetry Python SDK. Let me know if you  have issues with this.

nominate maintainers for python

---

README.md

Do not commit prior to 2019/05/08 11:00 PST, as this will be the final OpenCensus community meeting. Future occurrences have already been repurposed for OpenTelemetry.

Added details for the community meeting

---

community-members.md

Based on OpenCensus work.
@deadtrickster please let me know if you OK with the nomination. Either like or comment on this PR. Also - your company affiliation if any.
Note, this is not a full list of maintainer, but a single person nomination

Nominate Erlang maintainers

---

community-members.md

Bumping from Approver to maintainer. Carlos is currently the primary maintainer of the OpenTracing Java API, and a TSC member.

Nominate Carlos Alberto as Java Maintainer

---

community-members.md

Let's manage membership by inviting people in the org. Otherwise it's a bit confusing
Invited Isobel and Austin as members to the OpenTelemetry

Removed members

---

community-members.md

@tylerbenson has been working in observability since ancient times, and has given the OpenTracing project a lot of helpful design feedback, especially in Java.

Nominate Tyler Benson as a Java Approver

---

community-members.md

As discussed offline, I added the list of people who are committed to contribute to OpenTelemetry across all project we are going to contribute to.

Add Dynatrace people as contributors

---

README.md

Add the new python SIG calendar. cc @tedsuo

Add Python SIG info to README

---

README.md

Fix a typo in the README: we're in PDT now, not PST. I'm assuming this meeting schedule will change before we fall back on 11/3. @SergeyKanzhelev.

Change PST to PDT

---

README.md

Quick change to fix the time since it's 8AM on the calendar now.
We may switch this back to 9AM after the next meeting, but the README should be accurate in the meantime.

Make Python SIG 8AM

---

community-members.md

This is a quick change to make the repo links consistent in the membership doc. Previously the links only existed for the java and website repos.

Add repo links to community-members doc

---

community-members.md

Based on omnition contributions in OC and OT

Nominating Tigran for specs approvers.

---

community-members.md

Just a minor edit -- SIGs for C++ and Erlang are formed already. I've removed those languages from "Others" section.

Remove C++ & Erlang from others section as SIGs are formed

---

README.md

seems like this was copy-pasted from the .NET SIG info including its ID

Fix conference dial-in info

---

community-members.md

Top contributor to OpenTracing Ruby:
https://github.com/opentracing/opentracing-ruby/graphs/contributors
https://github.com/opentracing/opentracing-ruby/commits?author=mwear

Nominating @mwear as Ruby maintainer

---

README.md

This PR updates the link for the python SIG meeting to point at the shared public calendar instead of the old python-specific one. Other languages will likely have to make the same change.

Link to shared calendar for python SIG

---

community-members.md

Justin Smith is no longer associated with OpenTelemetry project due to other assignments. Replacing him with Daniel Khan (Approver -> Maintainer).
- Reviewer of the codebase for at least 3 months
- Reviewer for at least 10 substantial PRs to the codebase
1. https://github.com/open-telemetry/opentelemetry-js/pull/89#discussion_r301921527
1. https://github.com/open-telemetry/opentelemetry-js/pull/57#discussion_r298848930
1. https://github.com/open-telemetry/opentelemetry-js/pull/60#discussion_r298711319
1. https://github.com/open-telemetry/opentelemetry-js/pull/148#pullrequestreview-269100583
1. https://github.com/open-telemetry/opentelemetry-js/pull/136#pullrequestreview-269109173
1. https://github.com/open-telemetry/opentelemetry-js/pull/154#discussion_r310158038
1. …

Update JavaScript maintainers

---

community-membership.md

Namely, "Steering Committee" is the "Governance Committee" and the "TSC" is the "TC" in OpenTelemetry.

Fix some un-updated terminology

---

README.md

As per doodle poll, the calendar time has changed from Tuesdays at 3pm pacific to Thursdays at 10am pacific to allow for European timezone participation.
TODO: we also need a new calendar that is publicly visible for this.

opentelemetry-go SIG meeting time change

---

community-members.md

The opentelemetry-erlang repo has only in the past month started having PRs for review, so the 3 months of reviewing requirement can not be met. But @ferd has given substantial reviews on our most recent PRs that are defining the structure of the project https://github.com/open-telemetry/opentelemetry-erlang/pulls
Fred in general is a good fit as an approver due to his experience with Erlang, both developing and teaching, plus writing 3 books on the subject:
- https://learnyousomeerlang.com/
- http://www.erlang-in-anger.com/
- http://propertesting.com/

add Fred Hebert as an approver for Erlang lib

---

docs/how-to-configure-new-repository.md

maintainers should be maintainers

---

COMMUNICATION.md

I feel that the first paragraph, even though factually correct and explanatory, mischaracterized the code of conduct as an offensive mechanism rather than the promise to be inclusive. Changing language a little bit.
Also added one item about frustration with open source some people may experience.
The best way to look at changes is to look at this commit: https://github.com/open-telemetry/community/commit/492129c32df8ef694203555cca3f65300346d244

Communication doc: improvements

---

README.md

I'm just going to merge this – prev link was a 404, basically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-telemetry/community/193)

Fix Gitter link

---

README.md

@trask , if you want to re-use the same zoom room for the meeting - please make it half an hour so it will not be back to back to the next one also using the same room. Alternatively, perhaps @tedsuo can change zoom room to another one for GoLang SIG

Removed timezone from the link

---

README.md

1. Added meeting info for C/C++ SIG.
2. Fixed missing period notes for consistency.

Add C/C++ SIG meeting

---

README.md

The first reference of the community calendar was attached to the monthly community meeting. I added a dedicated section for the closer to the top of the page.

Made the community calendar more prominent

---

README.md

Adds PHP SIG info to the community page. This assumes we can reuse the zoom meeting ID from the kick-off meeting.
cc @bobstrecansky

Add PHP SIG

---

community-members.md

Based on discussion in the initial PHP SIG meeting, Bob Strecansky and Dmitry Krokhin have volunteered to maintain the repo, and Brain Akins has volunteered to review and approve code.
Since this is a bootstrapping operation, there are no prior commits or existing community members to point to.

Initial community members for PHP SIG

---

community-members.md

Remove iredelmeier as a JS approver

---

community-members.md

Rahul has worked on the OpenCensus Service that served as basis for the Collector and is a maintainer on Go (same source language of the Collector). See #216 for his previous contributions.
Fixes #216
/cc @rghetia

Add Rahul Patel as approver for Collector

---

community-members.md

Currently there is no much activity in the C/C++ SDK.
@reyang has kicked off the initial C++ SDK community meeting, and will be driving this effort going forward. Reiley has been working on C++ compiler and debugger around 10 years ago.
@maxgolov is the current owner of the Microsoft internal C++ telemetry SDK, which is used across Azure/Office/Windows. He has wide experience working on embedded operating systems, drivers and low level stack.

Add Max and Reiley as the Approver and Maintainer for C++ SDK

---

community-members.md

Don Morrison is an active contributor to the OpenTelemetry Ruby project, contributing 5 PRs to date. He'd like to start triaging issues for the project as well.

Add elswkid as Approver for Ruby

---

community-members.md

John made a lot of contributions to the Java repo implementing a bunch of critical features like the name tracer, SpanData transition from proto, etc.
John also actively review a lot of PRs.

Add John Watson as approver for Java

---

community-members.md

Josh has done quite a bit of work, writing and approving specification requests. I would like to nominate him as a Specification approver.
History of spec work: https://github.com/open-telemetry/opentelemetry-specification/pulls?utf8=%E2%9C%93&q=jmacd+
I know we're switching SIGs to manage their own lists; raising this request here until that work is complete.

Add Josh MacDonald as Specification approver

---

community-members.md

@dazuma is the top contributor to OpenCensus Ruby and has been helping with infrastructure on OpenTelemetry Ruby. We'd be happy to have him as a maintainer.
See:
* https://github.com/census-instrumentation/opencensus-ruby/graphs/contributors
* https://github.com/census-instrumentation/opencensus-ruby/commits?author=dazuma
* https://github.com/open-telemetry/opentelemetry-ruby/pull/124
* https://github.com/open-telemetry/opentelemetry-ruby/pull/138

Decentralize Ruby Maintainers and approvers list

---

README.md

Per https://github.com/open-telemetry/community/pull/243#issuecomment-549500880

Link to the OTel brand assets in the CNCF repo

---

CODEOWNERS

Reverts open-telemetry/community#277 and goes back to individually tagging people.

Revert "Sync CODEOWNERS to governance committeee"

---

community-membership.md

There isn't a definition for the `owner` role, but looking at the detailed requirements below, it looks like the intention was for this to be `approvers` instead.

Fix role name inconsistency

---

README.md

I wanted to fix the link since it was broken, but figured it would also be nice to add a few words of description.

Fix EEF Observability group link

---

community-members.md

We shouldn't need to update the community readme when we add/remove individual approvers, only maintainers.

redirect go approvers list.

---

community-members.md
governance-charter.md

Approvers criteria: make it easier to gain (and lose) approvership so that approvership more actively reflects the current set of trusted reviewers.
* Require approvers to be active at least once a month or else temporarily lose privileges (so we can trust `CODEOWNERS` to contain people who will actually be available to review pulls)
* Reduce requirement to 1 month and 10 non-trivial reviews, rather than 3 months and 30 reviews to become an approver, given our current state of maturity and length of time the project has existed.
* Explicitly specify that if an approver loses confidence of a maintainer, they can be removed from approvership, to address concerns that 1 month may be too speedy to permanently assess someone's technical judgment.

change approvers criterion as per governance committee meeting

---

README.md

The Ruby SIG now meets on Thursday at 9 AM PT. This PR updates the README to reflect the new meeting time.

Update README with new Ruby SIG meeting time

---

maturity-matrix.yaml

Per the header comment for the file under review here:
>   OpenTelemetry is a complex project with many moving parts. Thankfully, we strive to keep those parts loosely coupled where we can (this has been a goal since the very announcement of OpenTelemetry, per this blog post: https://medium.com/opentracing/merging-opentracing-and-opencensus-f0fe9c7ca6f0)
> 
>   This file describes the structure of the project and its sub-components, definitions of API and stability maturity levels, and finally records the current maturity of each component. We maintain this file as YAML in order to make it easier to automate scripts (e.g., for the website) that present the data to OpenTelemetry end-users.
This PR stems from the most recent technical *and* governance committee meetings. cc @mtwo who is …

Incorporate an OTel-wide maturity matrix

---

community-members.md

* Remove @songy23 as he is no longer active in this project;
* Remove @AloisReitbauer as he is not active
* Add @arminru  to the specs approver list - @arminru had more than 30 PRs reviewed and is active since July, 2019.

Remove and add new specs approvers

---

README.md

Added the usual info about SIGs. Todo: add the regular meeting day/time
after we choose one.
Resolves: https://github.com/open-telemetry/community/issues/307

Add entry for Log SIG

---

README.md

Clarify that metrics and logging are workgroups under the specification SIG

Clarify metrics and logging as part of spec SIG

---

README.md

We now meet 4PM every other week for contributors in APAC.

New times for python SIG meeting

---

README.md

Mornings do not work well for me and I suggest start alternating time for the SIG meeting.
@open-telemetry/dotnet-approvers  @open-telemetry/dotnet-maintainers do you have objections?

Suggest alternatig time for .NET SIG meetings

---

community-members.md

Moving our Approvers and Maintainers to be referenced in our repository.  I think I did this correctly (coinciding with https://github.com/open-telemetry/opentelemetry-php/pull/109) but I'd love for someone to double check my math!

Moving the PHP Community Members

---

README.md

In agreement with both the Java SIG and the Java Auto-Instrumentation SIG, we have expanded the scope of the Java Auto-Instrumentation SIG to also include (manual) library instrumentation (and we have renamed the opentelemetry-auto-instr-java repo to opentelemetry-java-instrumentation).
This should help us to better re-use code and tests across both auto-instrumentation and (manual) library instrumentation, and provide a consistent experience for users regardless of which approach they prefer.

Update Java Auto-Instrumentation SIG scope

---

community-members.md

Updated the capitalization of [Lightstep](https://lightstep.com/) company name that changed earlier this year.
While fixing the company name, I updated @iredelmeier company affiliation because she is no longer at Lightstep.

update LightStep to Lightstep

---

community-members.md

I think we need to be on this page in order to be able to open a CNCF helpdesk ticket (based on my reading of https://github.com/cncf/servicedesk#how-do-i-file-a-ticket-with-the-service-desk and the linked spreadsheet).
Thanks!

Add Java Instrumentation to members page

---

community-membership.md
docs/how-to-configure-new-repository.md

This PR resolves https://github.com/open-telemetry/community/issues/350 by defining a Triage role in OpenTelemetry which matched the permissions and intent of the Triage role defined by GitHub. The goal of the triage role is to assist with applying the github workflows defined by the maintainers. Triagers are not required to write code, but are encouraged to be an active participant in the community.
Becoming a triager works as follows:
* Nominated by a Maintainer of the repository.
* Added to the triage team associated with the repository.
Note that Triagers are added on a project by project basis, and are not given triage permissions across the entire organization.

Define Triager role

---

README.md

We've been piggy-backing on the .NET SDK, but starting on 08/05, we would hold a separate meeting.

Add .NET Auto-Instrumentation meetings

---

community-membership.md

Just updating a table to include the approved triager role.

Add Triager to community membership table

---

README.md

This change reflects the reality, except not all government committee is on this list. So invited who was missing

Updating public comms description

---

README.md

Updating the meeting time per discussion on Gitter: https://gitter.im/open-telemetry/opentelemetry-dotnet-auto-instr?at=5f31beccfe39ca5d65939ae8

Change .NET Auto-Instrumentation meeting time to 1 PM PT

---

docs/how-to-configure-new-repository.md

Remove the requirement to make Admins group an admin of every repository. Org owners has enough permissions without this so this will remove an extra synchronization requirements.

No need for Admins group

---

README.md

The Python SIG decided to move the meetings back to a single time slot, 9am.

update python sig meeting time

---

README.md

There is already a link with the Gitter badge and there is no need for the explicit link to the Gitter chat.

Remove redundant link to OTel.NET Instr. Gitter

---

governance-charter.md

The only meaningful change here is that the GC would like to stabilize at 9 members long-term.

Update the governance charter per recent meetings

---

community-members.md

Changed link to say ruby instead of php.
Signed-off-by: Andrew Hsu <xuzuan@gmail.com>

fix link to otel ruby

---

community-members.md

Updating the top-level heading of this doc to clarify it is about
members because there already exists a document for community membership:
https://github.com/open-telemetry/community/blob/master/community-membership.md
Signed-off-by: Andrew Hsu <xuzuan@gmail.com>

update heading level 1 of members doc

---

README.md

While doing this, I thought about updating the link in this paragraph:
"All meetings happen over Zoom, are recorded and available on YouTube, and have a meeting notes document."
To the https://www.youtube.com/channel/UCHZDBZTIfdy94xMjMKz-_MA/playlists one.  I'll check on the #489.

#489 Added link to YoutTube recording of the GC

---

docs/how-to-configure-new-repository.md

GitHub now creates new repos with `main` as default branch.
https://github.com/github/renaming#new-repositories-use-main-as-default-branch-name

update howto config new repo for main branch

---

community-membership.md
docs/how-to-handle-public-calendar.md

This was discussed during the Jan. 11th, 2021 maintainers meeting.
1. Clarified that maintainers can schedule/organize SIG meetings.
2. Clarified the process on how to get write access to public calendar. (not sure if @SergeyKanzhelev will replace @mtwo)
@SergeyKanzhelev @mtwo please confirm.

Clarify maintains' access to public calendar

---

community-members.md

Fixing typo: C++ section mentions `Ruby maintainers` by mistake (paragraph was created by copy-paste of Ruby section).

Fix copy-paste issue in C++ paragraph

---

CONTRIBUTING.md
tech-committee-charter.md

This change is as discussed at a GC meeting in December. Happy to take feedback and/or discuss the proposal if the TC is concerned about feasibility. cc @open-telemetry/technical-committee @open-telemetry/governance-committee

Update the TC responsibilities w.r.t. donations

---

docs/how-to-configure-new-repository.md

The Maintain role is no longer in beta, see https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization.

Minor update to the repo configuration guidelines

---

README.md

Added Zoom password, but did not embed it so that it isn't scraped by bots. Removed the community call section as we haven't held it for almost a year (it was replaced by the weekly maintainers meeting).

Added Zoom password, removed montly community call

---

README.md

This was discussed a few times in the SIG meeting. We do not see much participation for the alternate time so changing to always have the meeting at the same time.

Update Collector SIG meeting times

---

README.md

Forgot to add this when we first set up the weekly maintainers calls last spring

Add maintainers weekly call to meetings list

---

README.md

http://slack.cncf.io/ <-- new users need to go here first to create an account.

Add instructions for creating a new CNCF slack account

---

community-membership.md

Removed the Gitter community link, and added links to get an invite and join the Slack community channel.

Update Gitter->Slack in community-membership requirement

---

docs/how-to-configure-new-repository.md

In https://github.com/open-telemetry/oteps/issues/144 and https://github.com/open-telemetry/opentelemetry-specification/issues/1333 CodeQL security scanning was enabled for most of our repositories and [most of them](https://codecov.io/gh/open-telemetry) already have Codecov coverage scanning set up. I think we should mention this in the new repo best practices so it's also considered right from the start when new repositories are created.

Add security and coverage scanning to best practices for new repos

---

README.md

Swapping meeting-ids for Wednesday meetings of `.Net Auto Instrumentation` and `C/C++`. This ensures there are no back-to-back meetings on Wednesday sharing the same meeting-id. 
Have discussed and agreed with @pjanotti on slack before raising the PR. If needed, please add @open-telemetry/dotnet-instrumentation-maintainers as the reviewers.
As a side-effect, VSCode has updated the `Table of Contents` as per the latest content.

Change meeting-ids for C/C++ and .Net Auto Instrumentation

---

README.md

Meeting timeslot and meeting notes doc updated as stated in https://github.com/open-telemetry/community/issues/632#issuecomment-870696413.

Update Sampling SIG meeting details

---

community-members.md

Josh is active member of a community, who was working on various aspects of OpenTelemetry like metrics GA, stability or APIs and semantic conventions. The work included prototyping, writing specs and documents, and driving consensus on numerous meetings.
Technical Community voted unanimously to welcome Josh as a new TC member.
CC:
- @open-telemetry/technical-committee 
- @open-telemetry/governance-committee 
- @jsuereth 
Congratulations, Josh!

jsuereth was voted as a new TC member

---

.github/ISSUE_TEMPLATE/donation.md
CONTRIBUTING.md

(This is a do-over of #829 – I had to recreate the PR because of branch protections. What follows is from the original PR description...)
Most of these were previously understood but not properly documented. The step about the marketing guidelines is meant to be consistent with the GC discussions at our meetings over the past two weeks.
cc @open-telemetry/governance-committee @open-telemetry/technical-committee
@SergeyKanzhelev I've incorporated several of your suggestions here.

Specify the steps in the OTel donation process [take two]

---

governance-charter.md

we are no longer using CIVS due to lack of github integration (since we don't know all participants' emails), and because CIVS requires email opt-in, having been (ab)used by RMS supporters to spam people

update voting method

---

README.md
assets.md
docs/how-to-handle-public-calendar.md

Updated our readme and documentation to reflect the recent improvements made to our calendar and Zoom links, which are now meeting-specific and are tied to a single CNCF Zoom account. Summary / justification:
I've updated all of our Zoom links in the calendar to use unique IDs. This has a few advantages:
- No more clashing meetings
- No more meetings from one SIG that unexpectedly flow into another SIG's call
- Meeting recordings should have titles now
There are some disadvantages:
- Meetings IDs and passwords are no longer predictable, meaning that meetings must be joined from the community calendar; I've removed static meeting links from the agenda docs and will remove them from GitHub
- Creating new meeting series will require access to the CNCF Zoom accounts
I made all of the edits …

Reflect calendar / Zoom updates

---

README.md

I added two sentences that describe the benefits of subscribing to community calendar updates through the calendar Google group.

Clarified benefits of community calendar group

---

community-membership.md

As this: https://github.com/open-telemetry/community/issues/921#issuecomment-978959069 reveals there is a mismatch of membership document and effective permissions.
By spirit, GC sets the rules of membership, and appoints who execute those rules. Since TC members are org admins, there are two ways to resolve this mismatch in membership document.
First option is to sponsor an automation that adds members and either automation or set of people appointed to check the membership requirements (company affiliation, approver+ status of sponsors). This is how [k8s is doing it](https://github.com/kubernetes/community/blob/master/community-membership.md#:~:text=once%20your%20sponsors%20have%20responded%2C%20your%20request%20will%20be%20reviewed%20by%20the%20kubernetes%20github%20admin%20team%2C%20in …

Make the TC responsible for adding new members

---

community-membership.md

As discussed at last week's governance meeting, here is a draft of the emeritus status for community members.

Add emeritus to the community membership

---

README.md
community-membership.md
governance-charter.md

As discussed last week, here is a draft of a process for electing new SIG maintainers.

Add a process for becoming a maintainer

---

README.md

As metrics specs are reaching Stable, it's important to cover it in the all-up specs SIG.
Removing the dedicated metrics meetings as we've decided to use the Tue. spec SIG meeting to cover the metrics topics.

Remove Metrics SIG meeting info

---

docs/how-to-configure-new-repository.md

In some cases, maintainers have admin permissions already. This officially allows that on a case-by-case basis.
The decision was made during the governance committee meeting on 2/17/2022 to temporarily grant admin permission to maintainers while the permissions differences between admin and maintain roles can be assessed. Currently, the rule is already inconsistently applied and many maintainers already have this permission and depend on it as part of their workflows. If it is determined that the maintain role is sufficient for maintainers, or that a custom role can be created, then it should be documented on an issue/PR and this can be updated then.
Related issues and PRs:
- Increase permission from `Write` to `Maintain` permission
- Issue #84
- PR #184
- Related discussion in #982
I …

Allow maintainers admin permissions on a case-by-case basis

---

README.md

Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
Created based on https://cloud-native.slack.com/archives/C01N6P7KR6W/p1644395453360869
This PR adds Kubernetes operator SIG/WG. The purpose of the meeting is to discuss operator-related topics.
Given the operator community is not the largest the scope could be expanded to talk about everything Kubernetes deployment-related. For instance the scope could include opentelemetry-operator and opentelemetry-helm-charts. Right now there is already some level of integration between the operator and helm charts  (e.g. the helm chart that deploys the operator).
cc) @jpkrohling @VineethReddy02 @asuresh4

Add Kubernetes operator SIG

---

README.md

As discussed in the otel-cpp community meeting, adjusting the meeting timing to better accommodate the community members across different time zones w.e.f. 23rd March. Google calendar is already updated. 
@open-telemetry/cpp-maintainers for visibility.

Update C++ SIG meeting time

---

community-members.md

I had already left the GitHub team a while ago but forgot about this text. Mainly want to avoid being part of the triage flow
https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#issue-triaging

Remove anuraaga from spec approvers

---

README.md
community-members.md

Added Demo application SIG information to the community readme.md & added a repo placeholder 
Referencing this issue: https://github.com/open-telemetry/community/issues/1038

Add Demo Application SIG to Community Readme

---

community-members.md

Follow up https://github.com/open-telemetry/opentelemetry-specification/pull/2594#issuecomment-1152798393.
Thanks @arminru for noticing this!

Remove John Watson from Metrics Approvers

---

community-members.md

remove -webstore link to reflect new repo
https://github.com/open-telemetry/opentelemetry-demo/issues/222

remove webstore from demo link

---

elections/2022/governance-committee-candidates.md
elections/2022/governance-committee-election.md

This change creates the skeleton directory for the 2022 elections,
providing the initial draft for the election document.
Fixes #1170

Create the skeleton for the 2022 elections

---

community-members.md

Jack has been actively driving log spec changes and the Logging SIG for many months now. The TC and current log spec approvers have unanimously agreed that Jack can be a great log spec approver.

Add Jack Berg as log spec approver

---

elections/2022/governance-committee-election.md

Additionally, adds the link to the Helios election.
Fixes #1182

Fix end time for the 2022 GC election

---

elections/2022/governance-committee-election.md

The blog post wasn't published on 14 September 2022 but should be published a day later. The form for exemption was also created so I added link to it here.

GC Elections - bumped blog post date, add google forms link

---

README.md

Wednesday's otel-cpp SIG meeting is overlapping with the Log SIG meeting, which makes it difficult for the members to attend both meetings if needed. Preponing the time for Wed meeting by 30 minutes to avoid this overlap. 
This has been discussed and agreed upon in last week's SIG meeting here - https://docs.google.com/document/d/1i1E4-_y4uJ083lCutKGDhkpi3n4_e774SBLi9hPLocw/edit?usp=sharing.
Once this is approved and merged, we will update the SIG repo README.md and the google calendar.
@open-telemetry/cpp-approvers  @open-telemetry/cpp-maintainers  @marcalff

Update OpenTelemetry C++ SIG meeting time.

---

elections/2022/governance-committee-election.md

The current link is the last year's election announcement.

Fix the link to "2022 Election announcements"

---

elections/2022/governance-committee-candidates.md

Looks like someone else's nomination accidentally added a header formatting to the whole paragraph for my nomination :) This reverts that.
It also updates the table of contents and makes the horizontal rule formatting consistent

Remove markdown header formatting and update ToC

---

elections/2022/governance-committee-candidates.md

Follow up https://github.com/open-telemetry/community/pull/1239#issuecomment-1271754092.
This PR is pure editorial change:
1. sorted the names alphabetically to meet with the statement in https://github.com/open-telemetry/community/blob/main/elections/2022/governance-committee-candidates.md#list-of-candidates, I think @reese-lee did the initial clean up but later PR broke it again.
2. removed several trailing spaces
BTW, @reese-lee I noticed that your photo is missing (currently it is a broken link).

Sort the candidate names alphabetically

---

CODEOWNERS
community-members.md

Update the current GC based on the 2022 elections.
Related to: https://github.com/open-telemetry/community/issues/1169

Update GC after 2022 elections

---

assets.md

Closes #1302
(@mtwo has already made this change to the google group)

Update asset owners for opentelemetry-calendar-contributors

---

community-membership.md

In the OpenTelemetry Collector SIG meeting of 30-Nov-2022, we talked about the requirement we have right now in the OpenTelemetry Community for the triager role, stating that people in that role are expected to join meetings. This is difficult for people in timezones far away from the remaining of the community.
I propose to remove this as a requirement, while still requiring participation from the candidate to the triager role in the community.

Remove requirement to attend meetings for triagers

---

.github/workflows/issue-management-feedback-label.yml
.github/workflows/issue-management-stale-action.yml

I like this stale workflow, which requires maintainers to add a "needs author feedback" label to an issue or PR before the stale bot takes effect, and the "needs author feedback" label is automatically removed on any further comment by the issue or PR author.
These are some example issues where I would like to apply this label: #933, #1137, #690, #681.

Add 'needs author feedback' workflow

---

.github/repository-settings.md

Following the new guidance at https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#collaborators-and-teams:
> If requested, `foo-maintainers` will be granted `Admin` permissions, and in return they must document any changes they make to the repository settings in a file named `.github/repository-settings.md` in their repository (other than temporarily disabling "Do not allow bypassing the above settings", see branch protection rules below).

Document repo settings applied to community repo itself

---

.github/workflows/issue-management-stale-action.yml

I noticed the new stale action didn't add comment to issue b/c I used the wrong [option](https://github.com/actions/stale#list-of-input-options).

Fix stale issue/pr auto-comment

---

.github/dependabot.yml

Currently there's only one github action in this repo (but it's outdated):
https://github.com/open-telemetry/community/blob/95351dce4361381d57b640102972d71026680f6b/.github/workflows/issue-management-stale-action.yml#L12

Add dependabot to keep github action(s) up-to-date

---

README.md

Per discussion, add contact information for CNCF PR to the project README.

Add media contact info to readme

---

roadmap.md

- For context, this roadmap file is now published at https://opentelemetry.io/community/roadmap/ via a git submodule over this repo (as mandated by https://github.com/open-telemetry/opentelemetry.io/issues/1809).
- Closes:
- https://github.com/open-telemetry/opentelemetry.io/issues/2303
That is, this PR includes the following changes:
- Ran Prettier
- Applies fixes noted in https://github.com/open-telemetry/opentelemetry.io/pull/2176. /cc @reyang @svrnm 
- Fixes heading levels
- Fixes spelling
- Adds commented Hugo front matter so that we can remove the hacks added to the website's adjust-pages script
- Applies other minor copyedits
/cc @austinlparker @cartermp @svrnm

[editorial] Roadmap copyedits + Hugo front matter

---

mission-vision-values.md

- Backports editorial changes made to the mission page on the website before using this repo's version of the page for publishing moving forward.
- Adds Hugo front matter in comments
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1289
/cc @svrnm @cartermp

Backport of mission copyedits from website

---

mission-vision-values.md

Fixes Hugo front matter:
- linkTitle
- Path info for GH links (view source, etc)
- Adds a `weight` so that the page appears first in the section listing
/cc @cartermp @svrnm

[editorial] Fix Hugo front matter in  mission-vision-values.md

---

community-members.md

The TC (Technical Committee) members have discussed and decided to have @jack-berg joining the TC.

Add Jack Berg as a TC member

---

assets.md

Adds note about 2FA being available now in 1Password.
Removes note about maintainers needing to request access to org secret, because I believe the secret has been made available to all repos (need someone from @open-telemetry/technical-committee to confirm).
Adds note about additional scope that has been granted to the personal access token.

Update opentelemetrybot details

---

assets.md

I confirmed with .NET folks that this is no longer being used.
cc @open-telemetry/dotnet-maintainers @open-telemetry/dotnet-contrib-maintainers @open-telemetry/dotnet-instrumentation-maintainers

Remove unused Azure Pipeline from assets

---

CONTRIBUTING.md

Didn't find any reference of TSC in this repo. A search in the issues reveals it's an old abbreviation: #248 #161

Fix old abbreviation: TSC -> TC

---

community-members.md

Previously, we used the instrumentation working group list for these reviews.  
I've formally asked each member if they'd like to officially take Approver roles.  The list here is those that are willing to  officially take on the responsibility they previously had.
See: https://github.com/open-telemetry/opentelemetry-specification/pull/3398

Formalizing semconv approver list.

---

README.md

Now that Logs Bridge API/SDK spec is stable we are merging the Log SIG meeting into general spec meeting. This was discussed in Logs SIG last time.
If in the future active work on Logs spec resumes we will restore the separate meeting.

Merge Logs SIG meeting into general Specification meeting

---

docs/using-github-extensions.md

Two things:
* Fixes broken link, there's no "new link" yet, see https://github.com/open-telemetry/semantic-conventions/issues/11, but it was in outdated doc anyways, so ...
* Updates page to reflect current practices around @opentelemetrybot usage

Update "Using Github Apps, etc" page

---

ADOPTERS.md

- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/2947
- Replaces page content with a note that the page has moved, and a link to its new home.
- Depends on https://github.com/open-telemetry/opentelemetry.io/pull/2961

ADOPTERS: direct readers to the website page

---

README.md

There is no calender invite yet. I [requested access](https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md#gaining-calendar-permissions) to create one.
Ref https://github.com/open-telemetry/opentelemetry-specification/issues/3556
cc @mx-psi @jsuereth

add system conventions stability working group

---

assets.md

and remove Splain account from assets since no longer used (I have opened https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1840 to remove the Splain integration from the 5 OpenTelemetry zoom accounts)

Add Zapier account to assets

---

community-members.md

Was browsing this the other day and noticed that the spec / proto section of the community members doc still includes the semantic convention approvers. This has been split out and is now maintained in the `semantic-conventions` repo README.md.
Updating to reflect the current state of things.
cc @open-telemetry/specs-semconv-maintainers, @open-telemetry/specs-semconv-approvers

Breakout semantic conventions section of community members doc

---

code-of-conduct.md
mission-vision-values.md

This PR improves our code of conduct by stating how violations should be reported. It also adds a set of community values, showing what we expect from our community members when interacting with other members.

Add community values, improve code of conduct

---

mission-vision-values.md

Followup to:
- #1655
- https://github.com/open-telemetry/opentelemetry.io/pull/3299
Without this we get a build warning:
```console
$ npx prettier --check .
Checking formatting...
[warn] content-modules/community/mission-vision-values.md
[warn] Code style issues fixed in the above file.
```
/cc @svrnm

[editorial] Fix mission-vision-values.md formatting

---

docs/how-to-configure-new-repository.md

In the 10/25 TC meeting we discussed the github discussions feature:
* Should discussions be enabled in any opentelemetry repository?
* What is the value of / difference between discussions and issues?
* What is the value of / difference between discussions and other Q&A forums like CNCF slack and Stackoverflow?
The conclusions were:
* Discussions often overlap with issues - i.e. often discussions are feature requests in disguise.
* We shouldn't have discussions which are unchecked and unmoderated. This invites unhealthy conversation we want to discourage.
* Some communities like `opentelemetry-dotnet` have been using discussions quite affectively and we shouldn't be restrictive about their use when helpful.
This PR adds a note to the repository setup instructions about discussions, …

Discussions are opt in, maintainers responsible for moderation

---

governance-charter.md

There are no continuity members in the GC anymore, so this special note served it's purpose and can be safely removed.

Remove special note from GC charter elections policy

---

projects/one-logging-bridge-per-language.md

Roadmap project: One Logging Bridge per Language

---

CONTRIBUTING.md

This update follows discussion in the GC meeting about the donation process. In the meeting it was agreed that the GC should prescreen donation proposals before the TC is required to conduct due diligence and consider alternatives in order to reduce the workload on the TC.

Add GC pre-screening before TC diligence for donations

---

mission-vision-values.md
roadmap.md

- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/3922
/cc @theletterf @svrnm

[editorial] Fix path-base in Hugo front matter

---

README.md

One of the links for the calendar was still pointing to the old one

fix google calendar link

---

projects/security-semconv.md

https://github.com/open-telemetry/community/pull/1838 was merged to unblock the start of the project as all comments were resolved. However, there was a follow up action to change the usage of the term Working Group to SIG.
This PR changes usages of Working Group (and WG) to SIG. It also renames the file from `security.md` to `security-semconv.md` to avoid confusion with the Security SIG.

Clarifications on Security SemConv project and SIG

---

.cspell.yaml
community-members.md

@pellared has been very actively contributing and driving log spec improvements (https://github.com/open-telemetry/opentelemetry-specification/pulls/pellared)

Add pellared as log approver

---

areas-of-interest.md
community-members.md

Following the current guidelines, we are adding Liudmila Molkova to the TC. 
* Liudmila has been a very active OTel member (namely in the Specification and in Semantic Conventions), helping drive conversations and sponsoring different groups (Http, Messaging, Databases and LLM).
* Liudmila's specific Instrumentation knowledge and experience will help the TC to have a more complete coverage of the ecosystem.
* Bogdan Drutu and Armin Ruech sponsored her nomination.
* The TC voted to add Liudmila as a new member, with the GC confirming the addition.  
cc @open-telemetry/governance-committee @open-telemetry/technical-committee

Add Liudmila Molkova to the TC.

---

project-template.md

Update project template to:
- Indicate that both TC and GC members can sponsor projects.
- Add GC liaison as required staffing.
- Remove mentions of project tracking issue (as issues are tracked in project board)
- Add guidance about project board creation and management
- Add guidance about SIG info update in `sigs.yml`

Update project template to include board and SIG info guidance

---

community-members.md

We are trying to avoid both Agent (it can be misleading in .NET context, it is Java term) and Tracer (Metrics, Logs, (profiles)) are also supported by https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

Update .NET Auto-Instrumentation header

---

assets.md

Related to https://github.com/open-telemetry/opentelemetry.io/pull/4711 this lists that we make use of GCS using the admin@otel account

Add Google Custom Search to assets.md

---

assets.md

The Security SIG, along with the GC and TC, owns the GitHub organization `open-telemetry-private`, used store confidential information gathered by a privileged script. This organization wasn't mentioned before, and this PR fixes that.

Add mention of open-telemetry-private in assets

---

governance-charter.md

When I first read this, I thought that the points listed in the members of standing section were a union of requirements (e.g. both active and approver+). This PR attempts to reword it, as I understand the intent was either/both.

Clarify members of standing wrt Union

---

CONTRIBUTING.md

I see this pattern, and while I'm not a fan of very strict formatting, PRs should always at least say what they are doing, and why if they are non-trivial.

Suggest to write PR descriptions

---

projects/contributor-experience.md

Add `maryliag` to contributor-experience staff and also update the order to be alphabetical.

add maryliag to contributor-experience staff

---

.github/ISSUE_TEMPLATE/membership.md
CODEOWNERS
community-members.md
community-membership.md
elections/2021/governance-committee-candidates.md
guides/contributor/README.md
project-template.md
tech-committee-charter.md

The `community-membership.md` document [was recently moved to a new location](https://github.com/open-telemetry/community/pull/2051), but a lot of links to it weren't updated in the process. In this PR I:
- fix up links to it within this repository
- add a tombstone/redirect document as a stop-gap until the links in the [94 other places](https://github.com/search?q=org%3Aopen-telemetry%20community-membership.md&type=code) referencing the document across many different repos in the OTel organization are all fixed, to avoid sending people into a 404

Update `community-membership.md` links

---

.github/repository-settings.md

I noticed this because after clicking "Update Branch" on a PR with auto-merge enabled, it is merged right away (not waiting for the checks to run).
I intentionally didn't add `markdown-link-check` since it can be flaky when checking external links.
I have updated the repo settings already (so I don't forget), but I'll revert them if needed.

Add required status checks for PRs

---

governance-charter.md

I misunderstood that a member of standing was a member of the open-telemetry org, when it is actually based on contributors to it. In other words, you do not need to become a member to vote.
Using the word member to define a member was confusing to me as we also define member elsewhere. There, we say that member is a part of the org, and that takes process besides contributions. https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md#member
According to @jpkrohling
> member of standing is also independent: it's sufficient to have a minimum set of contributions, being a member or not

Clarify members of standing

---

projects/k8s-semconv.md

Since the K8s SemConv SIG has been accepted, this is a follow up from https://github.com/open-telemetry/community/pull/2352 to add the link of the project board.

Add K8s project board link

---

elections/2024/governance-committee-candidates.md

Identified in https://github.com/open-telemetry/community/issues/2307, this fixes @dyladan's entry adding a missing headline.

Add Daniel Dyla's heading to GC 2024 candidates

---

guides/contributor/membership.md

This is related to https://github.com/open-telemetry/community/pull/2381, making a recommendation to remove company affiliation as part of the emeritus process.

add note about emeritus company affiliations

---

docs/using-github-extensions.md

The linked workflow was removed in https://github.com/open-telemetry/semantic-conventions/pull/1497. The stale PR check linked now represents a similar concept.

Fix dead link to GHA workflow in semconv repo

---

.cspell.yaml
CODEOWNERS
community-members.md

- Adds @mx-psi to current members
- Updates term for re-elected members
- Adds @dyladan to emeritus GC members

Post-election changes to GC

---

project-template.md

This PR proposes a new section to the project template, requesting project proponents to identify the relevant people in the industry for this SIG. This would help us map where potential gaps are, and document who was invited to collaborate but refused. I believe this is very important to keep the new SIG process transparent.

Add 'people to contact' to project template

---

.github/ISSUE_TEMPLATE/gc_member_onboarding.md

As identified in https://github.com/open-telemetry/community/issues/2410, this is no longer needed.

Remove calendar checks from GC member onboarding template

---

docs/how-to-handle-public-calendar.md

It looks like I updated the permissions on the doc already, but forgot to update it here.

Fix google group used for zoom bombing doc

---

projects/gen-ai.md

Before:
> <img width="561" alt="image" src="https://github.com/user-attachments/assets/8329033d-851f-4177-acf0-d9f23328a0a5" />
After:
> <img width="447" alt="image" src="https://github.com/user-attachments/assets/9c67c56f-3d59-412d-b471-0f9c5d883404" />
/cc @svrnm

[editorial] gen-ai: fix call-out markdown syntax

---

community-members.md

Just noticed that the network collector repos are not referenced in community-members.md. Added the two repositories and a link to triagers/approvers/maintainers

Add network collector to community-members.md

---

guides/contributor/processes.md

This came up in https://github.com/open-telemetry/opentelemetry-js/pull/5305 which is looking to include some ISC-licensed code in opentelemetry-js.git.
Refs: https://github.com/open-telemetry/community/issues/2504
---
Some notes:
- The original "At this moment, BSD and MIT are the only OSI-approved licenses known to be compatible" language came from https://github.com/open-telemetry/community/pull/479
- There is this older issue https://github.com/open-telemetry/community/issues/649 that may be resolved with this change? /cc @tigrannajaryan 
- FWIW, the ASF maintains a list of licenses it "identifies the acceptable licenses for inclusion of third-party Open Source components in Apache Software Foundation products.": https://www.apache.org/legal/resolved.html   However, the CNCF lists is …

Refer to CNCF allowlist for 3rd-party licenses approved for inclusion in CNCF repos

---

docs/how-to-configure-new-repository.md

Fixed couple gaps that I found while creating https://github.com/open-telemetry/opentelemetry-go-compile-instrumentation/.

Update the repo creation instructions

---

.cspell.yaml
assets.md

Related to #1549 and #2127.
This is more secure than using @opentelemetrybot (a repo can't grant more permissions that the app requests), and can be managed directly in the org (instead of as a separate github account with separate credentials).
May need other GitHub App "bots" with more permissions that are isolated to specific repos.
Opening as draft while I test things out in the Java instrumentation repo...

Add otelbot GitHub App to assets

---

assets.md
docs/how-to-configure-new-repository.md

Follow-up to @chalin's https://github.com/open-telemetry/community/pull/2548#discussion_r1952444032

Simplify glob pattern

---

README.md

After a lot of feedback and discussion, the GC / TC have decided to record TC meetings by default. However, in the event that sensitive topics are discussed, the portion of the meeting with sensitive topics will not be recorded.
cc @open-telemetry/governance-committee @open-telemetry/technical-committee

Indicate that TC meetings are now recorded

---

.github/ISSUE_TEMPLATE/gc_member_onboarding.md
project-management.md
projects/README.md

Updates links to the new [Projects](https://github.com/orgs/open-telemetry/projects/135/views/1) board which focuses solely on Projects, split from the original [Spec + OTEPs](https://github.com/orgs/open-telemetry/projects/29/views/6)

Update links to projects board

---

assets.md

Now that GitHub supports them for all public repos via a `windows-11-arm` runner: https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview/
Also, it looks like no one is using the `otel-windows-arm64` runners: https://github.com/search?q=org%3Aopen-telemetry%20%22otel-windows-arm64%22&type=code

Remove otel-windows-arm64 runners

---

.lychee.toml

Seems ok to leave these historical docs as-is and not try to keep the links up-to-date.

Exclude historical docs from link checker

---

CODEOWNERS

It was sort of obfuscated that they weren't already since everyone in the TC was a GitHub admin prior to #2749 which made their approvals carry green checkmarks.

Add the Technical Committee as approvers for the community repo

---

assets.md

~(my understanding is that we have have 3 named accounts that are allowed to administer the dockerhub account, I believe @tigrannajaryan, @jsuereth, and one other person?)~
UPDATE: see https://github.com/open-telemetry/community/pull/2645#issuecomment-2849252112

List admins for dockerhub account

---

assets.md
tech-committee-charter.md

As discussed in GC / TC meetings, we are moving GitHub administration over to @open-telemetry/admins (which is a smaller group with six members across both the GC and TC).
Also see #2749.

Remove GitHub administration from Technical Committee charter

---

guides/contributor/processes.md

This came up in #2774. 
The guidelines we link to seem to mostly talk about unmodified code (such as dependencies that are copied in full to the consuming repository). The newly added link gives additional guidance on what to do with code that is incorporated directly into the codebase (with potential modifications).

Refer to the CNCF Recommendations for Attribution Notices

---

.cspell.yaml
tech-committee-charter.md

Updates the Technical Committee charter to qualify the phrase "The TC members are expected to be active leaders in the project" 
- Defines three classes of SIG sponsorship: _Escalation_, _Guiding_, _Leading_
- Adds requirements to TC members to participate in these sponsorships
- At least one _Escalation_ sponsorship, with all SIGs having coverage across TC of this style sponsorship
- At least two of _Guiding_ or _Leading_ sponsorship.
- At most two of _Leading_ sponsorship.
The OpenTelemetry project has grown significantly over the past five years.  It has seen expansion into additional signals (logs, profiles) and rapid growth of project beyond just SDKs and Collectors (-contrib instrumentations, otlp-arrow, OpAMP, Weaver, Semantic Conventions, Kubernetes operator, etc. etc.).  The …

Add sponsorship requirements to the technical committee charter.

---

docs/how-to-configure-new-repository.md

This updates the documented `**/**` branch protection rule to match the one that is installed on repos by default by the CNCF enterprise org.

Update `**/**` branch protection rule

---

docs/how-to-configure-new-repository.md

so it's no longer needed to add them to each repo

GC write permissions now come from org-level role

---

assets.md

More info on the rename in https://github.com/open-telemetry/community/issues/2801

Update self-hosted runner alias

---

.github/ISSUE_TEMPLATE/social-media-request.yml

Relative links in issue forms are rendered from the repo level, so `../social-media-guide.md` renders as https://github.com/open-telemetry/social-media-guide.md instead of https://github.com/open-telemetry/community/blob/main/social-media-guide.md.
This uses the full URL for the social media guide, and also points to the website for marketing guidelines.

Fix links in social media request form

---

docs/how-meeting-recordings-upload-works.md
docs/how-to-handle-public-calendar.md
policies/third-party-meeting-recordings.md

Related #2681
Adds a policy that bans zoom bots and third party recorders.
It wasn't entirely clear to me where to document this policy. `docs`, `guides`, and `tools` directory all seem to provide how-to guides and explainers. The GC and TC charters definitely contain policies, but neither seemed a good fit for this. Similarly, the README has a `calendar` section but it is more focused on helping people find meetings than it is on policing them. I created a `policies` directory in order to clarify that this is a policy and not just a suggestion, and also to make it easy to find. If this should be documented somewhere else, please let me know and I'm happy to move it, however I think we should have a more clear distinction between what is a rule and what is a guide or suggestion anyway …

Create meeting recording policy

---

guides/maintainer/github-admin-processes.md

Requires approval from one representative from each SIG for admin changes for repositories owned by multiple SIGs.
Follows #2859.
Relates to open-telemetry/admin/pull/143.

[docs/guides/maintainers] Clarify admin workflow for repositories owned by multiple SIGs

---

project-management.md
project-template.md
roadmap-management.md
sigs.yml

* Adds clarifications on how community projects relate to SIGs, GitHub projects, and wider OpenTelemetry roadmap.
* Removes text in the project template to link to project management documentation instead.
* Clarifies required project staffing and sponsorship, especially for existing SIGs.
* Adapts project lifecycle and communication mechanisms to align with OpenTelemetry roadmap.
* Adds documentation about OpenTelemetry roadmap management.
* Adds current community projects to `sigs.yml` (this will be missing some roadmap items, which can be added before PR is merged)
I will leave this PR as draft until the changes to `sigs.yml`, along with the scripts/actions to handle syncing between projects and issues in `.roadmap` (still named `.project` at the time of writing) are merged. These will …

Add roadmap management docs and adapt project management guidance

---

community-members.md

1. #2376 added @lzchen as a spec sponsor without removing him from the emeritus
2. #2626 missed one line

Fix couple minor issues

---

scripts/gc-elections/generate-voters-roll.py

The current election voter roll script uses the `All` repository group when querying for voter eligibility (taken from [this view](https://opentelemetry.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All)). This used to return all contributors, including those with less than 20 contributions.
The current behaviour seen is that this same filter now stops at a certain spot depending on the range of the query, and when using the `Last year` filter, it stops at 25.
The change in this PR changes the `All` repository group to `opentelemetry`, which still contains contributions to all repositories, to a lowest value of 13 (see [this …

Use opentelemetry group for election roll

---

tech-committee-charter.md

The Technical committee has not operated with a chair since its founding. We have recently set up a rotation schedule for running both the Specification and TC meetings which has been performing the duties of the TC chair in our charter.
This PR simply removes the TC Chair position and denotes this rotational responsibility.
If we decide we want/need  chair position going forward we can add it back later.

Remove TC Chair position

---

docs/using-github-extensions.md

Updated link reference for OpenTelemetry Bot documentation.
This should fix the failing `markdown-link-check`.
Follow-up on #3011.
cc @trask

Fix link to OpenTelemetry Bot user documentation

---

elections/2025/governance-committee-election.md

The current wording makes it seem like anyone can run without any requirements. While anybody can run, they need three sponsors (and they need the "Maximal representation" clause, but that does not apply in this election cycle)

[elections/2025] Clarify that there are requirements to be fulfilled

---

community-members.md

Follow-up from @arminru's https://github.com/open-telemetry/community/pull/3040#discussion_r2395278133

Remove Josh MacDonald from TC emeritus section

---

elections/2025/voters-roll.csv

After leaving Jemmic I no longer have access to the @christophe-kamphaus-jemmic GitHub account and I'm only using @kamphaus.

[elections/2025] Remove previous account from GC voter list
